### ISSUE TITLE
TLSNotary server wont start without `private-key-pem-path` defined even when its unused

### ISSUE THREAD

**Issue by pirate** [tlsnotary/tlsn#565]
I just set up a TLSNotary server here: https://tlsnotary.zervice.io/ and [wrote a guide for others](https://docs.monadical.com/s/UrN0j1lpu) in the process, but I encountered a minor issue in the process that I think is a bug.

TLSNotary fails to start when any of `private-key-pem-path`, `certificate-pem-path`, or `whitelist-csv-path` are missing from `config.yaml`, even when the `tls` and `authorization` sections are disabled with `enabled: false`.

According to the (excellent) docs, those files should not be needed when those features are disabled:
<img width="400" alt="image" src="https://github.com/user-attachments/assets/e73e90d1-06cb-4fe4-aaa4-71c3044d5690">

---

### Error Output

```bash
tlsnotary-1  | Location:
tlsnotary-1  |     /usr/src/tlsn/notary/server/src/util.rs:7:21)
tlsnotary-1  | Error: Unexpected(tls: missing field `private-key-pem-path` at line 20 column 3
tlsnotary-1  | Location:
tlsnotary-1  |     /usr/src/tlsn/notary/server/src/util.rs:7:21)
tlsnotary-1  | Error: Unexpected(authorization: missing field `whitelist-csv-path` at line 30 column 3
```

---

### Steps to reproduce

Full steps to reproduce here: https://docs.monadical.com/s/UrN0j1lpu

`docker-compose.yml`:
```yaml
services:
    tlsnotary:
        # https://github.com/tlsnotary/tlsn/pkgs/container/tlsn%2Fnotary-server
        image: ghcr.io/tlsnotary/tlsn/notary-server:latest
        volumes:
          - ./tlsnotary:/root/.notary-server/config:ro
```

`./tlsnotary/config.yaml`:
```yaml
# copied from: https://github.com/tlsnotary/tlsn/blob/main/notary/server/config/config.yaml

server:
  name: "notary-server"
  host: "0.0.0.0"
  port: 80
  html-info: |
    <h1>Notary Server {version}!</h1>
    <ul>
    <li>git commit hash: <a href="https://github.com/tlsnotary/tlsn/commit/{git_commit_hash}">{git_commit_hash}</a></li>
    <li>git commit timestamp: {git_commit_timestamp}</li>
    <li>public key: <pre>{public_key}</pre></li>
    </ul>
    <a href="/healthcheck">health check</a> - <a href="/info">info</a><br/>

notarization:
  max-transcript-size: 20480

tls:
  enabled: false
  # BUG: these are unused when enabled=false, but tlsnotary will fail to start without them:
  # private-key-pem-path: "/letsencrypt/live/$DOMAIN/privkey.pem"
  # certificate-pem-path: "/letsencrypt/live/$DOMAIN/fullchain.pem"

notary-key:
  private-key-pem-path: "/root/.notary-server/config/notary.key"
  public-key-pem-path: "/root/.notary-server/config/notary.pub"

authorization:
  enabled: false
  # BUG: this must still be set even if auth is not enabled or it will fail to start:
  # whitelist-csv-path: "/root/.notary-server/config/whitelist.csv"

logging:
  level: DEBUG
```

If I create empty files in those locations and uncomment those lines in `config.yaml` then it starts without issue.
